name: diginlab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#db0a16'
    - '#1f0445'
    - '#199fcc'
    - '#f09425'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
